import Head from "next/head";
import styles from "@/styles/Home.module.css";
import MainLayout from "@/layouts/MainLayout";
import { useEffect } from "react";
import { getAllTests } from "@/store/functions";

export default function Home() {
  // useEffect(() => {
  //   getAllTests();
  // }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MainLayout>
          <h2>Admin panel</h2>
        </MainLayout>
      </main>
    </>
  );
}
